apiVersion: v1
kind: Service
metadata:
  name: user-app-service
spec:
  type: NodePort  # Using NodePort for Docker Desktop
  selector:
    app: user-app
  ports:
    - protocol: TCP
      port: 80  # External port for the service
      targetPort: 8080  # Internal port your app listens on
      nodePort: 30007  # Exposed port on the host machine (must be between 30000-32767)
